# -*- coding: utf-8 -*-
import re

LANGUAGE_CHOICES = (
	{'id': 'en', 'name': 'English'},
	{'id': 'nl', 'name': 'Nederlands'}
)

_KODI_TAGS = re.compile(r'\[(?:/?(?:B|I|UPPERCASE)|COLOR [^\]]+|/COLOR)\]')

_DUTCH = {
	'English': 'Engels',
	'Nederlands': 'Nederlands',
	'Menu Language': 'Menutaal',
	'Menu language changed': 'Menutaal gewijzigd',
	'Choose Media Type to Set Buttons': 'Mediatype kiezen om knoppen in te stellen',
	'Choose Button to Set': 'Knop kiezen om in te stellen',
	'Choose Action For %s': 'Actie kiezen voor %s',
	'Enable Content for Extras Lists': 'Content voor Extra-lijsten inschakelen',
	'Set Movie Buttons': 'Filmknoppen instellen',
	'Set TV Show Buttons': 'Serieknoppen instellen',
	'Restore Movie Buttons to Default': 'Filmknoppen herstellen naar standaard',
	'Restore TV Show Buttons to Default': 'Serieknoppen herstellen naar standaard',
	'Restore Movie & TV Show Buttons to Default': 'Film- en serieknoppen herstellen naar standaard',
	'Root': 'Hoofdmenu',
	'Movies': 'Films',
	'TV Shows': 'Series',
	'TV Show': 'Serie',
	'Anime': 'Anime',
	'Animes': 'Anime',
	'People': 'Personen',
	'Search': 'Zoeken',
	'Discover': 'Ontdekken',
	'Random Lists': 'Willekeurige lijsten',
	'My Lists': 'Mijn lijsten',
	'My Services': 'Mijn diensten',
	'Favorites': 'Favorieten',
	'Downloads': 'Downloads',
	'Tools': 'Tools',
	'Trending': 'Trending',
	'Trending Recent': 'Recent trending',
	'Popular': 'Populair',
	'Popular Today': 'Vandaag populair',
	'Premieres': 'Premieres',
	'Latest Releases': 'Nieuwste releases',
	'Most Watched': 'Meest bekeken',
	'Most Favorited': 'Meest favoriet',
	'Top 10 Box Office': 'Top 10 box office',
	'Blockbusters': 'Blockbusters',
	'In Theaters': 'In de bioscoop',
	'Up Coming': 'Binnenkort',
	'Upcoming': 'Binnenkort',
	'Oscar Winners': 'Oscarwinnaars',
	'Genres': 'Genres',
	'Providers': 'Aanbieders',
	'Networks': 'Netwerken',
	'Languages': 'Talen',
	'Years': 'Jaren',
	'Decades': 'Decennia',
	'Certifications': 'Certificeringen',
	'Because You Watched...': 'Omdat je keek...',
	'Because You Watched': 'Omdat je keek',
	'Watched': 'Bekeken',
	'Recently Watched': 'Recent bekeken',
	'In Progress': 'Bezig',
	'Recently Watched Episodes': 'Recent bekeken afleveringen',
	'In Progress Episodes': 'Afleveringen bezig',
	'Next Episodes': 'Volgende afleveringen',
	'Anime Trending': 'Anime trending',
	'Anime Trending Recent': 'Anime recent trending',
	'Anime Popular': 'Anime populair',
	'Anime Popular Recent': 'Anime recent populair',
	'Anime Premieres': 'Anime premieres',
	'Anime Most Watched': 'Anime meest bekeken',
	'Anime Most Favorited': 'Anime meest favoriet',
	'Anime On the Air': 'Anime nu op tv',
	'Anime Upcoming': 'Anime binnenkort',
	'Anime Genres': 'Anime genres',
	'Anime Providers': 'Anime aanbieders',
	'Anime Years': 'Anime jaren',
	'Anime Decades': 'Anime decennia',
	'Anime Certifications': 'Anime certificeringen',
	'Cloud Storage': 'Cloudopslag',
	'History': 'Geschiedenis',
	'Account Info': 'Accountinfo',
	'Search Videos': 'Videos zoeken',
	'Search Images': 'Afbeeldingen zoeken',
	'Trakt Collection': 'Trakt collectie',
	'Trakt Watchlist': 'Trakt watchlist',
	'Trakt My Lists': 'Trakt mijn lijsten',
	'Trakt Liked Lists': 'Trakt gelikete lijsten',
	'Trakt Favorites': 'Trakt favorieten',
	'Trakt Recommended': 'Trakt aanbevolen',
	'Trakt Calendar': 'Trakt kalender',
	'Trending User Lists': 'Trending gebruikerslijsten',
	'Popular User Lists': 'Populaire gebruikerslijsten',
	'Search User Lists': 'Gebruikerslijsten zoeken',
	'Movie Lists': 'Filmlijsten',
	'TV Show Lists': 'Serielijsten',
	'Anime Lists': 'Anime lijsten',
	'Trakt Lists': 'Trakt lijsten',
	'Because You Watched Lists': 'Omdat je keek lijsten',
	'Collection': 'Collectie',
	'Watchlist': 'Watchlist',
	'Recommended': 'Aanbevolen',
	'Movies Collection': 'Filmcollectie',
	'TV Shows Collection': 'Seriecollectie',
	'Recently Added Movies': 'Recent toegevoegde films',
	'Recently Added TV Shows': 'Recent toegevoegde series',
	'Recently Aired Episodes': 'Recent uitgezonden afleveringen',
	'Movies Watchlist': 'Filmwatchlist',
	'TV Shows Watchlist': 'Seriewatchlist',
	'Recommended Movies': 'Aanbevolen films',
	'Recommended TV Shows': 'Aanbevolen series',
	'Favorite Movies': 'Favoriete films',
	'Favorite TV Shows': 'Favoriete series',
	'Search History Movies': 'Zoekgeschiedenis films',
	'Search History TV Shows': 'Zoekgeschiedenis series',
	'Search History AI Search': 'Zoekgeschiedenis AI zoeken',
	'Search History Anime': 'Zoekgeschiedenis anime',
	'Search History People': 'Zoekgeschiedenis personen',
	'Search History Keywords (Movies)': 'Zoekgeschiedenis trefwoorden (films)',
	'Search History Keywords (TV Shows)': 'Zoekgeschiedenis trefwoorden (series)',
	'Keywords (Movies)': 'Trefwoorden (films)',
	'Keywords (TV Shows)': 'Trefwoorden (series)',
	'AI Search': 'AI zoeken',
	'Download Manager': 'Downloadbeheer',
	'Premium Files': 'Premium bestanden',
	'Images': 'Afbeeldingen',
	'Settings': 'Instellingen',
	'External Scraper Settings': 'Externe scraper-instellingen',
	'Tips for Use': 'Gebruikstips',
	'Set Views': 'Weergaven instellen',
	'Changelog & Log Utils': 'Changelog en logtools',
	'TV Shows Progress Manager': 'Serievoortgang beheren',
	'Shortcut Folders Manager': 'Snelkoppelingsmappen beheren',
	'Database & Cache Maintenance': 'Database- en cache-onderhoud',
	'Toggle Language Invoker (ADVANCED!!)': 'Language invoker omschakelen (GEAVANCEERD!!)',
	'Check for Corrupt Databases': 'Controleer op beschadigde databases',
	'Clean Databases': 'Databases opschonen',
	'Remake Settings Cache': 'Instellingencache opnieuw maken',
	'Clear All Cache (Excluding Favorites)': 'Alle cache wissen (behalve favorieten)',
	'Clear Favorites Cache': 'Favorietencache wissen',
	'Clear Search History Cache': 'Zoekgeschiedenis-cache wissen',
	'Clear Main Cache': 'Hoofdcache wissen',
	'Clear Meta Cache': 'Metacache wissen',
	'Clear Lists Cache': 'Lijstcache wissen',
	'Clear Trakt Cache': 'Trakt-cache wissen',
	'Clear IMDb Cache': 'IMDb-cache wissen',
	'Clear Internal Scrapers Cache': 'Interne scraper-cache wissen',
	'Clear External Scrapers Cache': 'Externe scraper-cache wissen',
	'Clear Real Debrid Cache': 'Real Debrid-cache wissen',
	'Clear Premiumize Cache': 'Premiumize-cache wissen',
	'Clear All Debrid Cache': 'All Debrid-cache wissen',
	'Clear Off Cloud Cache': 'Off Cloud-cache wissen',
	'Clear Easy Debrid Cache': 'Easy Debrid-cache wissen',
	'Clear TorBox Cache': 'TorBox-cache wissen',
	'Set Menus': 'Menuweergave instellen',
	'Set Movies': 'Filmweergave instellen',
	'Set TV Shows': 'Serieweergave instellen',
	'Set Seasons': 'Seizoensweergave instellen',
	'Set Episodes': 'Afleveringsweergave instellen',
	'Set Episode Lists': 'Afleveringslijsten instellen',
	'Set Premium Files': 'Premium bestanden instellen',
	'Changelog': 'Changelog',
	'Kodi Log Viewer': 'Kodi-logviewer',
	'Kodi Log Viewer (Old)': 'Kodi-logviewer (oud)',
	'Upload Kodi Log to Pastebin': 'Kodi-log uploaden naar Pastebin',
	'History': 'Geschiedenis',
	'[B]NEW SEARCH...[/B]': '[B]NIEUWE ZOEKOPDRACHT...[/B]',
	'[I]Make New Shortcut Folder...[/I]': '[I]Nieuwe snelkoppelingsmap maken...[/I]',
	'[I]Add Content...[/I]': '[I]Content toevoegen...[/I]',
	'[I]Make New Discover List...[/I]': '[I]Nieuwe ontdek-lijst maken...[/I]',
	'Set view and then click here': 'Stel de weergave in en klik hier',
	'menus': 'menu\'s',
	'episode lists': 'afleveringslijsten',
	'premium files': 'premium bestanden',
	'movie': 'film',
	'tvshow': 'serie',
	'episode': 'aflevering',
	'season': 'seizoen',

	'Move': 'Verplaatsen',
	'Remove': 'Verwijderen',
	'Add Content': 'Content toevoegen',
	'Restore Menu': 'Menu herstellen',
	'Check for New Menu Items': 'Nieuwe menu-items zoeken',
	'Reload Menu': 'Menu herladen',
	'Browse Removed items': 'Verwijderde items bekijken',
	'Remove from history': 'Uit geschiedenis verwijderen',
	'Clear All History': 'Alle geschiedenis wissen',
	'Rename': 'Naam wijzigen',
	'Delete Shortcut Folder': 'Snelkoppelingsmap verwijderen',
	'Make New Shortcut Folder': 'Nieuwe snelkoppelingsmap maken',
	'Make Random': 'Willekeurig maken',
	'Remove Random': 'Willekeurig verwijderen',
	'Clear All': 'Alles wissen',
	'Folder': 'Map',
	'File': 'Bestand',
	'Item': 'Item',
	'Delete Folder': 'Map verwijderen',
	'Delete File': 'Bestand verwijderen',
	'Delete Item': 'Item verwijderen',
	'Download File': 'Bestand downloaden',
	'Rename Folder': 'Map hernoemen',
	'Rename File': 'Bestand hernoemen',
	'Rename Item': 'Item hernoemen',
	'Like List': 'Lijst liken',
	'Unlike List': 'Lijst unliken',
	'Make New List': 'Nieuwe lijst maken',
	'Delete List': 'Lijst verwijderen',
	'Playback': 'Afspelen',
	'Browse': 'Bladeren',
	'Extras': 'Extra\'s',
	'Options': 'Opties',
	'Playback Options': 'Afspeelopties',
	'Browse Movie Set': 'Filmcollectie bekijken',
	'Browse Recommended': 'Aanbevolen bekijken',
	'Browse More Like This': 'Meer zoals dit bekijken',
	'In Trakt Lists': 'In Trakt-lijsten',
	'Trakt Lists Manager': 'Trakt-lijsten beheren',
	'Favorites Manager': 'Favorieten beheren',
	'Mark Watched': 'Als bekeken markeren',
	'Mark Unwatched': 'Als onbekeken markeren',
	'Clear Progress': 'Voortgang wissen',
	'Refresh Widgets': 'Widgets vernieuwen',
	'Reload Widgets': 'Widgets herladen',
	'Exit Movie List': 'Filmlijst sluiten',
	'Exit TV Show List': 'Serielijst sluiten',
	'Open Download Manager': 'Downloadbeheer openen',
	'Open Tools': 'Tools openen',
	'Open External Scraper Settings': 'Externe scraper-instellingen openen',
	'Open Settings': 'Instellingen openen',
	'Clear Scrapers Cache': 'Scraper-cache wissen',
	'Scrapers Options': 'Scraperopties',
	'Select Source': 'Bron kiezen',
	'Rescrape & Select Source': 'Opnieuw scrapen en bron kiezen',
	'Scrape with DEFAULT External Scrapers': 'Scrapen met STANDAARD externe scrapers',
	'Scrape with ALL External Scrapers': 'Scrapen met ALLE externe scrapers',
	'Scrape With All Filters Ignored': 'Scrapen met alle filters genegeerd',
	'Scrape with Custom Episode Groups Value': 'Scrapen met aangepaste afleveringsgroep',
	'Scrape with an Alias': 'Scrapen met alias',
	'Scrape with Custom Values': 'Scrapen met aangepaste waarden',
	'Playback Options': 'Afspeelopties',
	'Play Random': 'Willekeurig afspelen',
	'Based On': 'Gebaseerd op',
	'Auto Play': 'Automatisch afspelen',
	'Autoplay Next Episode': 'Volgende aflevering automatisch afspelen',
	'Autoscrape Next Episode': 'Volgende aflevering automatisch scrapen',
	'Quality Limit': 'Kwaliteitslimiet',
	'Enable Scrapers': 'Scrapers inschakelen',
	'On': 'Aan',
	'Off': 'Uit',
	'None': 'Geen',
	'Currently': 'Momenteel',
	'No Results': 'Geen resultaten',
	'Cancelled': 'Geannuleerd',
	'Success': 'Gelukt',
	'Error': 'Fout',
	'Failed': 'Mislukt',
	'Please Wait..': 'Even geduld..',
	'Press Info Button for More Info': 'Druk op Info voor meer info',
	'Press Context Button for Search': 'Druk op Context om te zoeken',
	'Press Context Button To Like List': 'Druk op Context om lijst te liken',
	'Press Context Button To UnLike List': 'Druk op Context om lijst te unliken',
	'More Info': 'Meer info',
	'No Image Path to Download': 'Geen afbeeldingspad om te downloaden',
	'Delete': 'Verwijderen',
	'Exit Images': 'Afbeeldingen sluiten',
	'Info': 'Info',
	'Add to Cloud': 'Aan cloud toevoegen',
	'Download Pack': 'Pack downloaden',

	'Trailer': 'Trailer',
	'Extra Info': 'Extra info',
	'Director': 'Regisseur',
	'Plot': 'Plot',
	'Keywords': 'Trefwoorden',
	'Close All Dialogs': 'Alle dialogen sluiten',
	'Cast': 'Cast',
	'More Like This': 'Meer zoals dit',
	'Reviews': 'Recensies',
	'Comments': 'Reacties',
	'Trivia': 'Trivia',
	'Blunders': 'Fouten',
	'Parental Guide': 'Oudergids',
	'Videos': 'Videos',
	'More from Year': 'Meer uit dit jaar',
	'More from Genres': 'Meer uit genres',
	'More from Networks': 'Meer uit netwerken',
	'More from Collection': 'Meer uit collectie',
	'Likes': 'likes',
	'Like': 'like',
	'No Finish Time': 'Geen eindtijd',
	'Finish Watching': 'Klaar met kijken',
	'Finish Rewatching': 'Klaar met opnieuw kijken',
	'Last Aired': 'Laatst uitgezonden',
	'Next Aired': 'Volgende uitzending',
	'Next Episode': 'Volgende aflevering',
	'No Episodes Available': 'Geen afleveringen beschikbaar',
	'No Trailer Found': 'Geen trailer gevonden',
	'No Director Information Available': 'Geen regisseur-informatie beschikbaar',
	'Youtube Plugin needed for playback': 'YouTube-plugin nodig voor afspelen',
	'Options...': 'Opties...',
	'Title': 'Titel',
	'Year': 'Jaar',
	'Season': 'Seizoen',
	'Episode': 'Aflevering',
	'Yes': 'Ja',
	'No': 'Nee',
	'Scrape with ALL External Scrapers?': 'Scrapen met ALLE externe scrapers?',
	'Scrape with DEFAULT External Scrapers?': 'Scrapen met STANDAARD externe scrapers?',
	'Disable All Filters for Search?': 'Alle filters uitschakelen voor zoeken?',
	'Filter Results': 'Resultaten filteren',
	'Enter Keyword (Comma Separated for Multiple)': 'Trefwoord invoeren (komma gescheiden voor meerdere)',
	'Filter by Title...': 'Filteren op titel...',
	'Filter by Info...': 'Filteren op info...',
	'Show Uncached Only': 'Alleen uncached tonen',
	'Press BACK to Cancel': 'Druk op BACK om te annuleren',
	'Sex & Nudity': 'Seks en naakt',
	'Violence & Gore': 'Geweld en gore',
	'Profanity': 'Grof taalgebruik',
	'Alcohol, Drugs & Smoking': 'Alcohol, drugs en roken',
	'Frightening & Intense Scenes': 'Angstaanjagende en intense scenes',
	'NO RANK': 'GEEN SCORE'
}

_DYNAMIC = (
	(re.compile(r'^Next Page \((.+)\) >>$'), lambda m: 'Volgende pagina (%s) >>' % m.group(1)),
	(re.compile(r'^Search Results for (.+)$'), lambda m: 'Zoekresultaten voor %s' % m.group(1)),
	(re.compile(r'^Because You Watched (.+)$'), lambda m: 'Omdat je %s keek' % m.group(1)),
	(re.compile(r'^Recommended based on (.+)$'), lambda m: 'Aanbevolen op basis van %s' % m.group(1)),
	(re.compile(r'^More Like This based on (.+)$'), lambda m: 'Meer zoals dit op basis van %s' % m.group(1)),
	(re.compile(r'^(.+) In Trakt Lists$'), lambda m: '%s in Trakt-lijsten' % m.group(1)),
	(re.compile(r'^Mark Watched (.+)$'), lambda m: 'Markeer bekeken: %s' % m.group(1)),
	(re.compile(r'^Mark Unwatched (.+)$'), lambda m: 'Markeer onbekeken: %s' % m.group(1)),
	(re.compile(r'^Re-Cache (Movies|TV Shows) Info$'), lambda m: '%s-info opnieuw cachen' % localize(m.group(1))),
	(re.compile(r'^Clear (.+) Cache$'), lambda m: '%s-cache wissen' % localize(m.group(1))),
	(re.compile(r'^Movies Random (.+)$'), lambda m: 'Willekeurige films: %s' % localize(m.group(1))),
	(re.compile(r'^TV Shows Random (.+)$'), lambda m: 'Willekeurige series: %s' % localize(m.group(1))),
	(re.compile(r'^Anime Random (.+)$'), lambda m: 'Willekeurige anime: %s' % localize(m.group(1))),
	(re.compile(r'^Random Because You Watched Movies$'), lambda m: 'Willekeurige films omdat je keek'),
	(re.compile(r'^Random Because You Watched TV Shows$'), lambda m: 'Willekeurige series omdat je keek'),
	(re.compile(r'^(.+)% Watched$'), lambda m: '%s%% bekeken' % m.group(1)),
	(re.compile(r'^Finish Watching: (.+)$'), lambda m: 'Klaar met kijken: %s' % m.group(1)),
	(re.compile(r'^Finish Rewatching: (.+)$'), lambda m: 'Klaar met opnieuw kijken: %s' % m.group(1)),
	(re.compile(r'^Last Aired: (.+)$'), lambda m: 'Laatst uitgezonden: %s' % m.group(1)),
	(re.compile(r'^Next Aired: (.+)$'), lambda m: 'Volgende uitzending: %s' % m.group(1)),
	(re.compile(r'^Next Episode: (.+)$'), lambda m: 'Volgende aflevering: %s' % m.group(1)),
	(re.compile(r'^Currently: (.+)$'), lambda m: 'Momenteel: %s' % localize(m.group(1))),
	(re.compile(r'^Assign an Episode Group to (.+)$'), lambda m: 'Afleveringsgroep toewijzen aan %s' % m.group(1)),
	(re.compile(r'^Currently (.+)$'), lambda m: 'Momenteel %s' % localize(m.group(1))),
	(re.compile(r'^Button (.+)$'), lambda m: 'Knop %s' % m.group(1)),
	(re.compile(r'^Based On (.+)$'), lambda m: 'Gebaseerd op %s' % m.group(1)),
	(re.compile(r'^(Auto Play|Quality Limit) \((.+)\)$'), lambda m: '%s (%s)' % (localize(m.group(1)), localize(m.group(2)))),
	(re.compile(r'^Show (.+) Only$'), lambda m: 'Alleen %s tonen' % m.group(1))
)

def ui_language():
	try:
		from modules import kodi_utils
		language = kodi_utils.get_property('fenlight.ui_language')
	except:
		language = ''
	return language or 'en'

def localize(text):
	if text in (None, ''): return text
	if ui_language() != 'nl': return text
	try: text = str(text)
	except: return text
	if text in _DUTCH: return _DUTCH[text]
	stripped = _KODI_TAGS.sub('', text)
	translated = _DUTCH.get(stripped)
	if not translated:
		for pattern, replacement in _DYNAMIC:
			match = pattern.match(stripped)
			if match:
				translated = replacement(match)
				break
	if translated:
		if stripped == text: return translated
		if stripped in text: return text.replace(stripped, translated, 1)
		return translated
	return text

def localize_context_menu(items):
	return [(localize(label), action) for label, action in items]

def localize_items(items, *keys):
	for item in items:
		for key in keys:
			if key in item: item[key] = localize(item[key])
	return items
